theme: jekyll-theme-cayman
title: A Gentle Introduction to Word Embeddings for the Computational Social Sciences
description: Companion website for our workshop at the 2019 European Symposium Series on Societal Challenges in Computational Social Science (September 2 - 4, 2019 in Zurich, Switzerland).